### PR TITLE
Jason

### PR DESCRIPTION
**Pull request by dpzwick**
Hey Jason,

How do you feel about this? I did a few things here:

- Removed particles, they are now in a ppiclF library that is coupled to CMT-nek
- I moved cmtchk out of just stage 1 so it is called other stage. This allows feedback forces and all particle stuff to be in the .usr file now since forces can be coupled every rk stage. Does this break anything?

Let me know if this is alright.

Best wishes,
David

### CODE REVIEW

**Comment by hackljf** [comment]
Great to hear from you, David! cmtchk is intended to replace/extend userchk. One of the major uses of userchk is ad hoc manipulation of initial conditions and execution forking BEFORE the time loop begins. However, CMT-nek's variables (notably U) are NOT fully initialized before the time loop. cmtchk exists to provide this functionality in CMT-nek. It also avoids an extra call to compute_primitive_vars because, somehow, SOLN gets changed after cmt_nek_advance and userchk is not reliable for CMT-nek.

Your changes will break cmtchk. The very least we could do is

1. put something like
`if [ $CMT -ne 0 ]; then
if ! cat $CASENAME.f | grep -qi "subroutine.*cmtchk" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek. Unlike userchk, cmtchk is called
c at EVERY Runge-Kutta stage. Please do NOT place executable
c statements outside of the if-endif block below unless you know what
c you are doing. See [DAVID'S FANTASTIC EXAMPLE LIBRARIES] for
c an important example
      subroutine cmtchk
      include 'SIZE'
      include 'TOTAL'
      include 'CMTDATA'

      if (stage.eq.1) then
c everything you'd ever want to do in userchk goes here if you want CMT-nek to do it

      endif

      return
      end
_ACEOF
fi
fi`

in core/mkuserfile
and
2. explain this in a README somewhere.

thanks for the PR. It's real helpful and a wonderful reason to use git!

**Comment by dpzwick** [comment]
That is a good idea! Thanks for looking at this. I updated the mkuserfile and pvort case to reflect this. How does this look?

**Comment by dpzwick** [comment]
If you accept the commit I will add an example case with readme file here that has a build script to build everything.

**Comment by hackljf** [comment]
Can I test this on Friday?

**Comment by dpzwick** [comment]
Sure, sounds good!

**Pull request merged**
